data:
  sync_asset_path: "C:/Users/sureshs/Visual Studio/Visual Studio Code Repo/ogipilot-demo-run/ogipilot-demo-run/data/SyncAssets.xml.erb"
  sync_segment_path: "C:/Users/sureshs/Visual Studio/Visual Studio Code Repo/ogipilot-demo-run/ogipilot-demo-run/data/SyncSegments.xml.erb"